### ISSUE TITLE
IKEv2 Username Password 

### ISSUE THREAD

**Issue by imnikksingh** [truemetal/ikev2_vpn#1]
Hi,

Thanks for the script!

I want to connect vpn (android / iphone) with IKEv2 username password. But it is not working with
strongSwan client (Android)  and default iphone clinet.

Kindly help me to resolve this issue. 

Thanks in advance.

**Comment by truemetal** [comment]
Hi @inder1989 

These scripts are based on this article: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ikev2-vpn-server-with-strongswan-on-ubuntu-16-04

There are examples in that article on how to configure on windows / macos and ios, I'd suggest you try them. 
I've tested this on macos (and i think ios as well, but not sure about that). 

Hope this helps.
Cheers

**Comment by truemetal** [comment]
Please feel free to let me know if you this does not work on iOS or macos though.

**Comment by truemetal** [comment]
There's a similar issue opened here: https://github.com/truemetal/ikev2_vpn/issues/2#issuecomment-363532496

I'll take a look and comment.

**Comment by imnikksingh** [comment]
Hi @truemetal ,

Thanks for looking into this. I really appreciate.

**Comment by imnikksingh** [comment]
Hi @truemetal 

Now I'm able to connect with iPhone. The problem was that I had not installed server-root-ca.pem on iphone. After installing certificate, connection started working fine on iphone. I followed all the steps from digitalocean which you've provided in above comment.

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ikev2-vpn-server-with-strongswan-on-ubuntu-16-04

For android I've added aes256-sha2_256 in ike (/etc/ipsec.conf) and after that it also started working with Android srongSwan app as well. Please check the below line for example:

ike=aes256-sha1-modp1024,3des-sha1-modp1024!,aes256-sha2_256

Thanks

**Comment by truemetal** [comment]
Hi @inder1989 

I've added and pushed `aes256-sha2_256` to both scripts; thanks for the contribution.

Since you (and couple of other people) had difficulty with connecting via 'certs way', I've recorded a demo video and it's now available on this repo's front page. 

Thanks
