### ISSUE TITLE
Проблема с подключением (cert / username-password auth)

### ISSUE THREAD

**Issue by jeudespr1t** [truemetal/ikev2_vpn#2]
Дроплет абсолютно чистый. Скачал, установил. Сертификат стоит. Не могу подключиться. Пробовал как с **Windows 10**, так и с **macOS**. В чём может быть проблема?

**Comment by truemetal** [comment]
В смысле, не получается подключиться к VPN с macos, используя скрипт `ikev2-deploy-certs.sh`?

**Comment by jeudespr1t** [comment]
Да.

**Comment by truemetal** [comment]
Ну ок, вторая жалоба именно на сертификаты - может на днях гляну. Попробуйте PSK - он точно работает.

**Comment by jeudespr1t** [comment]
PSK на **iOS** работает?

**Comment by truemetal** [comment]
На macos работает, iOS не помню.

**Comment by jeudespr1t** [comment]
Спасибо за старания!

**Comment by imnikksingh** [comment]
Hi @jeudespr1t ,

Я проверил PSK, и он отлично работает в iPhone (iOS)

**Comment by truemetal** [comment]
@inder1989 @jeudespr1t экая тут компания русскоговорящих собралась :)

@jeudespr1t я проверил, работает; учитывая что было несколько вопросов именно по этому скрипту, на главной странице теперь висит демо видео по деплою и подключению используя `ikev2-deploy-certs.sh`

**Comment by jeudespr1t** [comment]
Спасибо Вам большое! Премного благодарен. 👍
