### ISSUE TITLE
on demand .mobileconfig

### ISSUE THREAD

**Issue by wolvesoftheworld** [truemetal/ikev2_vpn#3]
Any chance you could help me build something like this -- especially the On Demand section -- that works for this setup?

https://wiki.strongswan.org/projects/strongswan/wiki/AppleIKEv2Profile

Thanks much!

**Comment by truemetal** [comment]
Hey @wolvesoftheworld !

I don't really have a drop-in experience I could just share on that, and I'm not interested to be trying it out now. 

I'd suggest that you start by creating some `.mobileconfig` and getting it to work, then building on top of that. 

Cheers

**Comment by wolvesoftheworld** [comment]
Right on.  Thanks much for building this!

**Comment by truemetal** [comment]
@wolvesoftheworld on the other hand, I might be available for hire to help on this in the next couple of weeks. Please feel free to drop me a line here should you be interested: https://ios-engineer.com

Anyways, I'm glad this helped!
