### ISSUE TITLE
Connection to "my_ip_address" closed by remote host

### ISSUE THREAD

**Issue by ddi98** [truemetal/ikev2_vpn#4]
hello and thank you so much for this script!,
when I try to install it suddenly the connection from the remote host is closed
![Immagine del 21-06-19 alle 11 56](https://user-images.githubusercontent.com/43742625/59914978-db8d2900-941b-11e9-8a19-42a0ba32ff00.jpg)

PS: would it be possible to adapt this fantastic script also on ubuntu 18.4?

**Comment by truemetal** [comment]
Hey @ddi98 

Thanks for your report! Judging by your screenshot, the process completed successfully.
Please just try connecting to your server again after it reboots.

Probably it's worth adding a log statement about that.

Regarding adapting to 18.4, unfortunately I don't have plans to do that in the foreseeable future.

Cheers

**Comment by truemetal** [comment]
> Probably it's worth adding a log statement about that.

Just added that.
Please let me know if that's not the case for you.

**Comment by truemetal** [comment]
> Regarding adapting to 18.4, unfortunately I don't have plans to do that in the foreseeable future.

Pull requests would be welcome though.

**Comment by ddi98** [comment]
hello, thanks for the reply, if the operation was successful where do I get the PSK? thank you

**Comment by truemetal** [comment]
Hey @ddi98 

Right on the start, the script outputs your generated PSK to the console and requires you to hit something to continue the execution.

Cheers

**Comment by ddi98** [comment]
thank you very much, I really missed the initial message where PSK returned!

I wanted to ask you another information, the vpn on my iphone after a few minutes of inactivity automatically disconnects, is it possible to make sure that the vpn never disconnects? thank you so much
