### ISSUE TITLE
the connection is lost after a few minutes of inactivity in sleep mode on the iphone

### ISSUE THREAD

**Issue by ddi98** [truemetal/ikev2_vpn#5]
hi, everything works great, but when I'm connected on the VPN from the iphone, after a few minutes, sometimes even after an hour in sleep mode the connection falls, is there any parameter I can change to prevent this from happening? thank you so much

**Comment by truemetal** [comment]
That's a good question. I was not able to achieve always-on VPN connection sustainability.

**Comment by truemetal** [comment]
@ddi98 how do you connect, using some 3rd party app or your code?

**Comment by ddi98** [comment]
I use the IOS native client

**Comment by ddi98** [comment]
> That's a good question. I was not able to achieve always-on VPN connection sustainability.
do you have any solution? it would be very useful to make sure that the connection never falls into a professional vpn

**Comment by ddi98** [comment]
do you have any solution? it would be very useful to make sure that the connection never falls into a professional vpn

**Comment by truemetal** [comment]
@ddi98 curiously, I don't see on-demand switch when manually entering details in iOS VPN settings. Though I can see this switch is there if I add a VPN config from code and include these:

```
NEVPNManager.shared().onDemandRules = [NEOnDemandRuleConnect()]
NEVPNManager.shared().isOnDemandEnabled = true
```

**Comment by truemetal** [comment]
Sadly, it also seems impossible to ensure that VPN is 100% enabled without using supervised device profile: 
https://labs.integrity.pt/articles/the-curious-case-of-apple-ios-ikev2-vpn-on-demand/
https://help.apple.com/deployment/ios/#/iore8b083096

**Comment by truemetal** [comment]
I'm going to close this issue, please feel free to reopen if you'll have any updates @ddi98
