### ISSUE TITLE
It does not work after I upgrading to strongSwan v5.7.2.

### ISSUE THREAD

**Issue by Zimong** [truemetal/ikev2_vpn#6]
![无标题](https://user-images.githubusercontent.com/12237255/61175532-e59de400-a5e3-11e9-861c-f4c086d6ed43.png)

**Comment by truemetal** [comment]
@Zimong so you run the script and it does not work or like you run the script, it works, but when updating the strong swan it then does not?

**Comment by Zimong** [comment]
I run the "ikev2-deploy-psk.sh" script , it works.
Some reasons I "apt-get -y dist-upgrade" the system, it does not work after reboot.
I run the script again, no any change.

**Comment by Zimong** [comment]
> @Zimong so you run the script and it does not work or like you run the script, it works, but when updating the strong swan it then does not?

@truemetal 
I run the "ikev2-deploy-psk.sh" script , it works.
Some reasons I "apt-get -y dist-upgrade" the system, it does not work after reboot.
I run the script again, no any change.

**Comment by truemetal** [comment]
@Zimong I've just repeated your steps: 

1. Deploy a fresh setup of vpn on 16.04 
2. run `apt-get -y dist-upgrade`
3. `reboot` the system

And I have v. 5.3.5 after these steps. Not sure, how you got v. 5.7.2 again please?

```
root@vpn-test:~# ipsec version
Linux strongSwan U5.3.5/K4.4.0-159-generic
Institute for Internet Technologies and Applications
University of Applied Sciences Rapperswil, Switzerland
See 'ipsec --copyright' for copyright information.
root@vpn-test:~#
```

**Comment by Zimong** [comment]
@truemetal 
Changed "/etc/apt/sources.list", 'dist-upgrade' from Ubuntu cosmic (18.10) StrongSwan v. 5.6.3 to Ubuntu disco (19.04) StrongSwan v. 5.7.2.
May roll back to the previous version to work?

**Comment by truemetal** [comment]
@Zimong you might try rolling back or manually downgrading strong swan or the system and then use the script as the reference to repeat the steps manually if needed after your downgrade.

Another option is to just redeploy a fresh server with 16.04 ubuntu.

If you get the script running on the later ubuntu version, please feel free to submit a pull request. 

Cheers
